import { User, UserRole } from "@/src/types";

export type Resource =
  | "projects"
  | "tasks"
  | "files"
  | "approvals"
  | "billing"
  | "messages"
  | "meetings"
  | "tickets"
  | "contracts"
  | "settings"
  | "admin"
  | "client_360"
  | "change_requests"
  | "maintenance"
  | "handover"
  | "credentials"
  | "analytics"
  | "integrations"
  | "api_keys";

export type Action = "read" | "create" | "update" | "delete" | "approve" | "pay";

const PERMISSION_MATRIX: Record<UserRole, Partial<Record<Resource, Action[]>>> = {
  super_admin: {
    projects: ["read", "create", "update", "delete"],
    tasks: ["read", "create", "update", "delete"],
    files: ["read", "create", "update", "delete"],
    approvals: ["read", "create", "update", "delete", "approve"],
    billing: ["read", "create", "update", "delete", "pay"],
    messages: ["read", "create", "update", "delete"],
    meetings: ["read", "create", "update", "delete"],
    tickets: ["read", "create", "update", "delete"],
    contracts: ["read", "create", "update", "delete"],
    settings: ["read", "update"],
    admin: ["read", "create", "update", "delete"],
    client_360: ["read", "create", "update", "delete"],
    change_requests: ["read", "create", "update", "delete", "approve"],
    maintenance: ["read", "create", "update", "delete"],
    handover: ["read", "create", "update", "delete", "approve"],
    credentials: ["read", "create", "update", "delete"],
    analytics: ["read"],
    integrations: ["read", "create", "update", "delete"],
    api_keys: ["read", "create", "update", "delete"],
  },
  admin: {
    projects: ["read", "create", "update"],
    tasks: ["read", "create", "update", "delete"],
    files: ["read", "create", "update", "delete"],
    approvals: ["read", "create", "update"],
    billing: ["read", "create", "update"],
    messages: ["read", "create"],
    meetings: ["read", "create", "update"],
    tickets: ["read", "create", "update"],
    contracts: ["read", "create", "update"],
    settings: ["read", "update"],
    admin: ["read", "update"],
    client_360: ["read"],
    change_requests: ["read", "create", "update"],
    maintenance: ["read", "update"],
    handover: ["read", "create", "update"],
    credentials: ["read"],
    analytics: ["read"],
    integrations: ["read", "update"],
    api_keys: ["read", "create"],
  },
  client_admin: {
    projects: ["read"],
    tasks: ["read", "create", "update"],
    files: ["read", "create"],
    approvals: ["read", "approve"],
    billing: ["read", "pay"],
    messages: ["read", "create"],
    meetings: ["read", "create"],
    tickets: ["read", "create"],
    contracts: ["read", "approve"],
    settings: ["read", "update"],
    admin: [],
    client_360: ["read"],
    change_requests: ["read", "create", "approve"],
    maintenance: ["read"],
    handover: ["read", "approve"],
    credentials: ["read"],
    analytics: ["read"],
    integrations: ["read"],
    api_keys: ["read"],
  },
  client_user: {
    projects: ["read"],
    tasks: ["read", "create"],
    files: ["read", "create"],
    approvals: ["read"],
    billing: ["read"],
    messages: ["read", "create"],
    meetings: ["read", "create"],
    tickets: ["read", "create"],
    contracts: ["read"],
    settings: ["read"],
    admin: [],
    client_360: [],
    change_requests: ["read", "create"],
    maintenance: ["read"],
    handover: ["read"],
    credentials: [],
    analytics: [],
    integrations: [],
    api_keys: [],
  },
  client: {
    projects: ["read"],
    tasks: ["read", "create", "update"],
    files: ["read", "create"],
    approvals: ["read", "approve"],
    billing: ["read", "pay"],
    messages: ["read", "create"],
    meetings: ["read", "create"],
    tickets: ["read", "create"],
    contracts: ["read", "approve"],
    settings: ["read", "update"],
    admin: [],
    client_360: ["read"],
    change_requests: ["read", "create", "approve"],
    maintenance: ["read"],
    handover: ["read", "approve"],
    credentials: ["read"],
    analytics: ["read"],
    integrations: ["read"],
    api_keys: ["read"],
  },
  developer: {
    projects: ["read"],
    tasks: ["read", "create", "update"],
    files: ["read", "create"],
    approvals: ["read"],
    billing: [],
    messages: ["read", "create"],
    meetings: ["read"],
    tickets: ["read", "update"],
    contracts: [],
    settings: ["read"],
    admin: [],
    client_360: [],
    change_requests: ["read", "update"],
    maintenance: ["read"],
    handover: ["read", "update"],
    credentials: [],
    analytics: [],
    integrations: [],
    api_keys: [],
  },
  designer: {
    projects: ["read"],
    tasks: ["read", "create", "update"],
    files: ["read", "create"],
    approvals: ["read", "create"],
    billing: [],
    messages: ["read", "create"],
    meetings: ["read"],
    tickets: ["read"],
    contracts: [],
    settings: ["read"],
    admin: [],
    client_360: [],
    change_requests: ["read"],
    maintenance: [],
    handover: ["read"],
    credentials: [],
    analytics: [],
    integrations: [],
    api_keys: [],
  },
  support_agent: {
    projects: ["read"],
    tasks: ["read"],
    files: ["read"],
    approvals: ["read"],
    billing: [],
    messages: ["read", "create"],
    meetings: ["read", "create"],
    tickets: ["read", "create", "update", "delete"],
    contracts: [],
    settings: ["read"],
    admin: [],
    client_360: ["read"],
    change_requests: ["read"],
    maintenance: ["read", "update"],
    handover: [],
    credentials: [],
    analytics: [],
    integrations: [],
    api_keys: [],
  },
  finance: {
    projects: ["read"],
    tasks: [],
    files: ["read"],
    approvals: [],
    billing: ["read", "create", "update", "delete"],
    messages: ["read", "create"],
    meetings: [],
    tickets: ["read"],
    contracts: ["read"],
    settings: ["read"],
    admin: [],
    client_360: ["read"],
    change_requests: ["read"],
    maintenance: ["read"],
    handover: [],
    credentials: [],
    analytics: ["read"],
    integrations: [],
    api_keys: [],
  },
  account_manager: {
    projects: ["read", "update"],
    tasks: ["read", "create", "update"],
    files: ["read", "create"],
    approvals: ["read", "create"],
    billing: ["read"],
    messages: ["read", "create"],
    meetings: ["read", "create", "update"],
    tickets: ["read", "create", "update"],
    contracts: ["read", "create"],
    settings: ["read"],
    admin: [],
    client_360: ["read", "update"],
    change_requests: ["read", "create", "update"],
    maintenance: ["read", "update"],
    handover: ["read", "create"],
    credentials: [],
    analytics: ["read"],
    integrations: [],
    api_keys: [],
  },
  project_manager: {
    projects: ["read", "create", "update"],
    tasks: ["read", "create", "update", "delete"],
    files: ["read", "create", "update"],
    approvals: ["read", "create", "update"],
    billing: ["read"],
    messages: ["read", "create"],
    meetings: ["read", "create", "update"],
    tickets: ["read", "create", "update"],
    contracts: ["read"],
    settings: ["read"],
    admin: [],
    client_360: ["read"],
    change_requests: ["read", "create", "update"],
    maintenance: ["read"],
    handover: ["read", "create", "update"],
    credentials: [],
    analytics: ["read"],
    integrations: [],
    api_keys: [],
  },
};

export function hasPermission(
  user: User | null | undefined,
  resource: Resource,
  action: Action
): boolean {
  if (!user) return false;
  const userRole = user.role || "client";
  const allowedActions = PERMISSION_MATRIX[userRole]?.[resource] || [];
  return allowedActions.includes(action);
}
